services:
  db:
    image: postgres:16-alpine
    container_name: todo-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5223:5432"
    volumes:
      - todo_db_data:/var/lib/postgresql/data
    networks:
      - todo_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 5

  app:
    image: tg/todo-app:1.1
    build:
      context: ../ToDoApp
      dockerfile: Dockerfile_KarimJapparov
    container_name: todo-app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      APP_PORT: ${APP_PORT}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${JPA_DDL_AUTO}
    networks:
      - todo_net

volumes:
  todo_db_data:

networks:
  todo_net:
    driver: bridge
